RSpec.describe KeycloakApiRails::Service do

  let!(:private_key)  { OpenSSL::PKey::RSA.generate(2048) }
  let!(:public_key)   { private_key.public_key }
  let!(:key_resolver)  { KeycloakApiRails::PublicKeyCachedResolverStub.new(public_key) }
  let!(:service)       { KeycloakApiRails::Service.new(key_resolver) }
  
  before(:each) do
    now = Time.local(2018, 1, 9, 12, 0, 0)
    Timecop.freeze(now)
  end

  after(:each) do
    Timecop.return
  end

  describe "#decode_and_verify" do
    def create_token(private_key, expiration_date, algorithm)
      claim = {
        iss: "KeycloakApiRails",
        exp: expiration_date,
        nbf: Time.local(2018, 1, 1, 0, 0, 0)
      }
      jws = JSON::JWT.new(claim).sign(private_key, algorithm)
      jws.to_s
    end

    context "when token is nil" do
      let(:token) { nil }
      it "should raise an error :no_token" do
        expect {
          service.decode_and_verify(token)
        }.to raise_error(KeycloakApiRails::TokenError,"No JWT token provided")
      end
    end

    context "when token is an empty string" do
      let(:token) { "" }
      it "should raise an error :no_token" do
        expect {
          service.decode_and_verify(token)
        }.to raise_error(KeycloakApiRails::TokenError,"No JWT token provided")
      end
    end

    context "when token is in an invalid format" do
      let(:token) { "coucou" }
      it "should raise an error :invalid_format" do
        expect {
          service.decode_and_verify(token)
        }.to raise_error(KeycloakApiRails::TokenError,"Wrong JWT Format")
      end
    end

    context "when token is in a valid format" do
      let(:algorithm)       { :RS256 }
      let(:expiration_date) { 1.week.from_now }

      context "and token is generated by another private key" do
        let(:another_private_key)  { OpenSSL::PKey::RSA.generate(1024) }
        let(:token)                { create_token(another_private_key, expiration_date, algorithm) }
        
        it "should raise an error :verification_failed" do
          expect {
            service.decode_and_verify(token)
          }.to raise_error(KeycloakApiRails::TokenError,"Failed to verify JWT token")
        end
      end

      context "and token is generated by the right private key" do
        let(:token) { create_token(private_key, expiration_date, algorithm) }
        
        context "and token is expired" do
          let(:expiration_date) { Time.now - 2.days }
          
          it "should raise an error :expiration_date" do
            expect {
              service.decode_and_verify(token)
            }.to raise_error(KeycloakApiRails::TokenError,"JWT token is expired")
          end
        end

        # The service reads `token_expiration_tolerance_in_seconds` when it is instantiated:
        # a token expiring within that tolerance is already considered as expired.
        context "and token expires within the expiration tolerance" do
          let(:expiration_date) { Time.now + 5 }

          it "should raise an error :expiration_date" do
            expect(KeycloakApiRails.config.token_expiration_tolerance_in_seconds).to eq 10
            expect {
              service.decode_and_verify(token)
            }.to raise_error(KeycloakApiRails::TokenError,"JWT token is expired")
          end
        end

        context "and token expires just after the expiration tolerance" do
          let(:expiration_date) { Time.now + 30 }

          it "should return a not-nil decoded token" do
            expect(KeycloakApiRails.config.token_expiration_tolerance_in_seconds).to eq 10
            expect(service.decode_and_verify(token)).to_not be_nil
          end
        end

        context "and token is not expired" do
          let(:expiration_date) { Time.now + 2.days }

          context "and token is encrypted using RS256" do
            let(:algorithm) { :RS256 }
            
            it "should return a not-nil decoded token" do
              expect(service.decode_and_verify(token)).to_not be_nil
            end
          end

          context "and token is encrypted using RS512" do
            let(:algorithm) { :RS512 }
            
            it "should return a not-nil decoded token" do
              expect(service.decode_and_verify(token)).to_not be_nil
            end
          end
        end
      end
    end
  end

  describe "#decode_and_verify claims" do
    let(:claims) { {} }
    let(:token)  { JSON::JWT.new({ "exp" => (Time.now + 3600).to_i }.merge(claims)).sign(private_key, :RS256).to_s }

    after(:each) do
      KeycloakApiRails.load_configuration
    end

    def service_configured_with(**options)
      options.each { |name, value| KeycloakApiRails.config.public_send("#{name}=", value) }
      KeycloakApiRails::Service.new(key_resolver)
    end

    describe "the 'exp' claim" do
      context "when the token carries none" do
        let(:token) { JSON::JWT.new("sub" => "a-user").sign(private_key, :RS256).to_s }

        it "should raise an error :missing_claim" do
          expect {
            service.decode_and_verify(token)
          }.to raise_error(KeycloakApiRails::TokenError, "JWT token does not carry the mandatory claim 'exp'")
        end
      end
    end

    describe "the 'aud' claim" do
      context "when no audience is expected" do
        let(:claims) { { "aud" => "another-api" } }

        it "should accept a token issued for any audience" do
          expect(service_configured_with(expected_audience: nil).decode_and_verify(token)).to_not be_nil
        end
      end

      context "when an audience is expected" do
        let(:decoding_service) { service_configured_with(expected_audience: "my-api") }

        context "and the token carries it" do
          let(:claims) { { "aud" => "my-api" } }

          it "should return a not-nil decoded token" do
            expect(decoding_service.decode_and_verify(token)).to_not be_nil
          end
        end

        context "and the token carries it among several audiences" do
          let(:claims) { { "aud" => ["another-api", "my-api"] } }

          it "should return a not-nil decoded token" do
            expect(decoding_service.decode_and_verify(token)).to_not be_nil
          end
        end

        context "and the token has been issued for another audience" do
          let(:claims) { { "aud" => "another-api" } }

          it "should raise an error :invalid_audience" do
            expect {
              decoding_service.decode_and_verify(token)
            }.to raise_error(KeycloakApiRails::TokenError, "JWT token has been issued for another audience")
          end
        end

        context "and the token carries no audience" do
          it "should raise an error :invalid_audience" do
            expect {
              decoding_service.decode_and_verify(token)
            }.to raise_error(KeycloakApiRails::TokenError, "JWT token has been issued for another audience")
          end
        end
      end

      context "when several audiences are expected" do
        let(:claims) { { "aud" => "the-second-api" } }

        it "should accept a token issued for any of them" do
          decoding_service = service_configured_with(expected_audience: ["the-first-api", "the-second-api"])

          expect(decoding_service.decode_and_verify(token)).to_not be_nil
        end
      end
    end

    describe "the 'typ' claim" do
      context "when no token type is expected" do
        let(:claims) { { "typ" => "ID" } }

        it "should accept a token of any type" do
          expect(service_configured_with(expected_token_type: nil).decode_and_verify(token)).to_not be_nil
        end
      end

      context "when the 'Bearer' token type is expected" do
        let(:decoding_service) { service_configured_with(expected_token_type: "Bearer") }

        context "and the token is an access token" do
          let(:claims) { { "typ" => "Bearer" } }

          it "should return a not-nil decoded token" do
            expect(decoding_service.decode_and_verify(token)).to_not be_nil
          end
        end

        # Keycloak signs the ID tokens of a realm with the very same key as its access tokens.
        context "and the token is an ID token" do
          let(:claims) { { "typ" => "ID" } }

          it "should raise an error :invalid_token_type" do
            expect {
              decoding_service.decode_and_verify(token)
            }.to raise_error(KeycloakApiRails::TokenError, "JWT token is not of the expected type")
          end
        end

        context "and the token carries no type" do
          it "should raise an error :invalid_token_type" do
            expect {
              decoding_service.decode_and_verify(token)
            }.to raise_error(KeycloakApiRails::TokenError, "JWT token is not of the expected type")
          end
        end
      end
    end

    describe "the 'nbf' claim" do
      let(:claims) { { "nbf" => (Time.now + 3600).to_i } }

      context "when 'verify_not_before' is disabled" do
        it "should accept a token that is not valid yet" do
          expect(service_configured_with(verify_not_before: false).decode_and_verify(token)).to_not be_nil
        end
      end

      context "when 'verify_not_before' is enabled" do
        let(:decoding_service) { service_configured_with(verify_not_before: true) }

        it "should raise an error :not_yet_valid for a token that is not valid yet" do
          expect {
            decoding_service.decode_and_verify(token)
          }.to raise_error(KeycloakApiRails::TokenError, "JWT token is not valid yet")
        end

        context "and the token became valid in the past" do
          let(:claims) { { "nbf" => (Time.now - 3600).to_i } }

          it "should return a not-nil decoded token" do
            expect(decoding_service.decode_and_verify(token)).to_not be_nil
          end
        end

        context "and the token carries no 'nbf' claim" do
          let(:claims) { {} }

          it "should return a not-nil decoded token" do
            expect(decoding_service.decode_and_verify(token)).to_not be_nil
          end
        end
      end
    end
  end

  describe "#need_middleware_authentication?" do

    let(:method)  { nil }
    let(:path)    { nil }
    let(:headers) { {} }


    before(:each) do
      KeycloakApiRails.config.skip_paths = {
        post:   [/^\/skip/],
        get:    [/^\/skip/]
      }
      @result = service.need_middleware_authentication?(method, path, headers)
    end

    context "when method is nil" do
      let(:method) { nil }
      let(:path)   { "/do-not-skip" }
      it "should return true" do
        expect(@result).to be true
      end
    end

    context "when path is nil" do
      let(:method) { :get }
      let(:path)   { nil }
      it "should return true" do
        expect(@result).to be true
      end
    end

    context "when method does not match the configuration" do
      let(:method) { :put }
      let(:path)   { "/skip" }
      it "should return true" do
        expect(@result).to be true
      end
    end

    context "when path does not match the configuration" do
      let(:method) { :get }
      let(:path)   { "/do-not-skip" }
      it "should return true" do
        expect(@result).to be true
      end
    end

    context "when method [get] and path do match the configuration" do
      let(:method) { :get }
      let(:path)   { "/skip" }
      it "should return false" do
        expect(@result).to be false
      end
    end


    context "when method [post] and path do match the configuration" do
      let(:method) { :get }
      let(:path)   { "/skip" }
      it "should return false" do
        expect(@result).to be false
      end
    end

    context "when the request is preflight" do
      let(:method)  { :options }
      let(:headers) { { "HTTP_ACCESS_CONTROL_REQUEST_METHOD" => ["Authorization"] } }
      let(:path)    { "/do-not-skip" }
      it "should return false" do
        expect(@result).to be false
      end
    end

    context "when configured as opt_in" do
      before do
        KeycloakApiRails.config.opt_in = true
        service2 = KeycloakApiRails::Service.new(key_resolver)
        @result = service2.need_middleware_authentication?(method, path, headers)
      end

      # The configuration is global: leaving 'opt_in' enabled would disable the authentication
      # of every example running afterwards.
      after do
        KeycloakApiRails.config.opt_in = false
      end

      it "should return false" do
        expect(@result).to be false
      end
    end
  end

  describe "#read_token" do
    let(:query_string)                { "" }
    let(:url)                         { "http://api.service.com/api/health?aParameter=true#{query_string}" }
    let(:headers)                     { {} }
    let(:header_token)                { "header_token" }
    let(:query_string_token)          { "query_string_token" }
    let(:allow_token_in_query_string) { false }

    before(:each) do
      KeycloakApiRails.config.allow_token_in_query_string = allow_token_in_query_string
      @token = KeycloakApiRails::Service.new(key_resolver).read_token(url, headers)
    end

    after(:each) do
      KeycloakApiRails.config.allow_token_in_query_string = false
    end

    context "when the token is provided in the Authorization headers" do
      let(:headers) do
        {
          "HTTP_AUTHORIZATION" => "Bearer #{header_token}"
        }
      end

      context "and not in the query string" do
        let(:query_string) { "" }
        it "returns the header token" do
          expect(@token).to eq header_token
        end
      end

      # The header wins: a token carried by a query string leaks into the browser history, the
      # referrers and the access logs.
      context "and also in the query string" do
        let(:query_string)                { "&authorizationToken=#{query_string_token}" }
        let(:allow_token_in_query_string) { true }

        it "returns the header token" do
          expect(@token).to eq header_token
        end
      end

      context "and the scheme is spelled in lowercase" do
        let(:headers) { { "HTTP_AUTHORIZATION" => "bearer #{header_token}" } }

        it "returns the header token" do
          expect(@token).to eq header_token
        end
      end

      context "and the scheme is separated by several spaces" do
        let(:headers) { { "HTTP_AUTHORIZATION" => "Bearer   #{header_token}" } }

        it "returns the header token" do
          expect(@token).to eq header_token
        end
      end

      # 'gsub(/^Bearer /, "")' used to strip the prefix from every line of the header.
      context "and the header spans several lines" do
        let(:headers) { { "HTTP_AUTHORIZATION" => "Bearer #{header_token}\nBearer another_token" } }

        it "only strips the scheme of the first line" do
          expect(@token).to eq "#{header_token}\nBearer another_token"
        end
      end
    end

    context "when the token is not provided in the Authorization headers" do
      let(:headers) do
        {
          "ANOTHER_HEADER" => header_token
        }
      end

      context "and not in the query string" do
        let(:query_string) { "" }
        it "returns an empty token" do
          expect(@token).to eq ""
        end
      end

      context "and query string is nil" do
        let(:query_string) { nil }
        it "returns an empty token" do
          expect(@token).to eq ""
        end
      end

      context "but in the query string" do
        let(:query_string) { "&authorizationToken=#{query_string_token}" }

        context "and the query string is not allowed to carry a token" do
          let(:allow_token_in_query_string) { false }

          it "returns an empty token" do
            expect(@token).to eq ""
          end
        end

        context "and the query string is allowed to carry a token" do
          let(:allow_token_in_query_string) { true }

          it "returns the query string token" do
            expect(@token).to eq query_string_token
          end
        end
      end
    end
  end
end